name: Enforce Jira ID in PR

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  enforce-jira-id:
    runs-on: ubuntu-latest
  

    steps:

      - name: Install jq
        run: sudo apt-get install jq
      
      - name: Check for Jira ID in PR title
        run: |
          PR_TITLE=$(curl -v -H "Accept: application/vnd.github.v3+json" "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}" | jq -r '.title')
          if [[ ! $PR_TITLE =~ [A-Z]+-[0-9]+ ]]; then
            echo "Error: Jira issue key is missing in the PR title."
            exit 1
          fi
